import $ from "jquery";
import "./app.scss";
import "./components/fancyBox";
import "./components/inputFile";
import "./components/lazy";
import "./components/mailer";
import "./components/mask";
import "./components/popups";
import "./components/quiz";
import "./components/scroll";
import "./components/scrollTop";
import "./components/sliders";
import "./components/tabs";
import "./components/timer";
import "./components/titelFade";
window.jQuery = $;
